import type { Category, Topic, Language } from './types'

const EN: Topic[] = [
  // Daily life
  { id: 'en-d1',  category: 'daily',    text: 'Your morning routine' },
  { id: 'en-d2',  category: 'daily',    text: 'How you spend your evenings' },
  { id: 'en-d3',  category: 'daily',    text: 'Your daily commute' },
  { id: 'en-d4',  category: 'daily',    text: 'Cooking a meal you love' },
  { id: 'en-d5',  category: 'daily',    text: 'A typical weekend' },
  { id: 'en-d6',  category: 'daily',    text: 'How you stay organized' },
  { id: 'en-d7',  category: 'daily',    text: 'Your sleep habits' },
  { id: 'en-d8',  category: 'daily',    text: 'Shopping for groceries' },
  // Opinion
  { id: 'en-o1',  category: 'opinion',  text: 'The best invention of the last 20 years' },
  { id: 'en-o2',  category: 'opinion',  text: 'Social media — good or bad?' },
  { id: 'en-o3',  category: 'opinion',  text: 'Remote work vs. office work' },
  { id: 'en-o4',  category: 'opinion',  text: 'Should everyone learn to code?' },
  { id: 'en-o5',  category: 'opinion',  text: 'Money vs. happiness' },
  { id: 'en-o6',  category: 'opinion',  text: 'Is it better to live in a city or the countryside?' },
  { id: 'en-o7',  category: 'opinion',  text: 'The importance of hobbies' },
  { id: 'en-o8',  category: 'opinion',  text: 'Should schools teach financial literacy?' },
  // Story
  { id: 'en-s1',  category: 'story',    text: 'A mistake that taught you something' },
  { id: 'en-s2',  category: 'story',    text: 'A trip that changed you' },
  { id: 'en-s3',  category: 'story',    text: 'The best decision you ever made' },
  { id: 'en-s4',  category: 'story',    text: 'A time you were really nervous' },
  { id: 'en-s5',  category: 'story',    text: 'Something you learned the hard way' },
  { id: 'en-s6',  category: 'story',    text: 'A moment you felt proud of yourself' },
  { id: 'en-s7',  category: 'story',    text: 'A childhood memory' },
  { id: 'en-s8',  category: 'story',    text: 'A time you helped someone' },
  // Describe
  { id: 'en-desc1', category: 'describe', text: 'Your ideal home' },
  { id: 'en-desc2', category: 'describe', text: 'Your city or neighborhood' },
  { id: 'en-desc3', category: 'describe', text: 'Your workspace' },
  { id: 'en-desc4', category: 'describe', text: 'Someone who inspires you' },
  { id: 'en-desc5', category: 'describe', text: 'Your favorite place in the world' },
  { id: 'en-desc6', category: 'describe', text: 'A book or film that stayed with you' },
  { id: 'en-desc7', category: 'describe', text: 'Your dream job' },
  { id: 'en-desc8', category: 'describe', text: 'A skill you want to develop' },
  // Abstract
  { id: 'en-a1',  category: 'abstract', text: 'What does success mean to you?' },
  { id: 'en-a2',  category: 'abstract', text: 'What makes a good friend?' },
  { id: 'en-a3',  category: 'abstract', text: 'What is courage?' },
  { id: 'en-a4',  category: 'abstract', text: 'What does home mean to you?' },
  { id: 'en-a5',  category: 'abstract', text: 'What would you do with unlimited time?' },
  { id: 'en-a6',  category: 'abstract', text: 'What is the hardest thing about being human?' },
  { id: 'en-a7',  category: 'abstract', text: 'What does creativity mean to you?' },
  { id: 'en-a8',  category: 'abstract', text: 'If you could change one thing about society' },
  // Word
  { id: 'en-w1',  category: 'word', text: 'Freedom' },
  { id: 'en-w2',  category: 'word', text: 'Time' },
  { id: 'en-w3',  category: 'word', text: 'Trust' },
  { id: 'en-w4',  category: 'word', text: 'Change' },
  { id: 'en-w5',  category: 'word', text: 'Silence' },
  { id: 'en-w6',  category: 'word', text: 'Fear' },
  { id: 'en-w7',  category: 'word', text: 'Ambition' },
  { id: 'en-w8',  category: 'word', text: 'Beauty' },
  { id: 'en-w9',  category: 'word', text: 'Work' },
  { id: 'en-w10', category: 'word', text: 'Memory' },
  { id: 'en-w11', category: 'word', text: 'Risk' },
  { id: 'en-w12', category: 'word', text: 'Comfort' },
  { id: 'en-w13', category: 'word', text: 'Patience' },
  { id: 'en-w14', category: 'word', text: 'Happiness' },
  { id: 'en-w15', category: 'word', text: 'Failure' },
  { id: 'en-w16', category: 'word', text: 'Nature' },
  { id: 'en-w17', category: 'word', text: 'Routine' },
  { id: 'en-w18', category: 'word', text: 'Loneliness' },
  { id: 'en-w19', category: 'word', text: 'Loyalty' },
  { id: 'en-w20', category: 'word', text: 'Power' },
]

const FR: Topic[] = [
  // Vie quotidienne
  { id: 'fr-d1',  category: 'daily',    text: 'Ta routine du matin' },
  { id: 'fr-d2',  category: 'daily',    text: 'Comment tu passes tes soirées' },
  { id: 'fr-d3',  category: 'daily',    text: 'Ton trajet quotidien' },
  { id: 'fr-d4',  category: 'daily',    text: 'Préparer un plat que tu aimes' },
  { id: 'fr-d5',  category: 'daily',    text: 'Un week-end typique' },
  { id: 'fr-d6',  category: 'daily',    text: 'Comment tu restes organisé(e)' },
  { id: 'fr-d7',  category: 'daily',    text: 'Tes habitudes de sommeil' },
  { id: 'fr-d8',  category: 'daily',    text: 'Faire les courses' },
  // Opinion
  { id: 'fr-o1',  category: 'opinion',  text: 'La meilleure invention des 20 dernières années' },
  { id: 'fr-o2',  category: 'opinion',  text: 'Les réseaux sociaux — bien ou mal ?' },
  { id: 'fr-o3',  category: 'opinion',  text: 'Télétravail ou bureau ?' },
  { id: 'fr-o4',  category: 'opinion',  text: 'Est-ce que tout le monde devrait apprendre à coder ?' },
  { id: 'fr-o5',  category: 'opinion',  text: 'L\'argent ou le bonheur ?' },
  { id: 'fr-o6',  category: 'opinion',  text: 'Mieux vivre en ville ou à la campagne ?' },
  { id: 'fr-o7',  category: 'opinion',  text: 'L\'importance des loisirs' },
  { id: 'fr-o8',  category: 'opinion',  text: 'L\'école devrait-elle enseigner la gestion financière ?' },
  // Histoire
  { id: 'fr-s1',  category: 'story',    text: 'Une erreur qui t\'a appris quelque chose' },
  { id: 'fr-s2',  category: 'story',    text: 'Un voyage qui t\'a changé(e)' },
  { id: 'fr-s3',  category: 'story',    text: 'La meilleure décision que tu aies prise' },
  { id: 'fr-s4',  category: 'story',    text: 'Un moment où tu étais vraiment stressé(e)' },
  { id: 'fr-s5',  category: 'story',    text: 'Quelque chose que tu as appris à la dure' },
  { id: 'fr-s6',  category: 'story',    text: 'Un moment de fierté' },
  { id: 'fr-s7',  category: 'story',    text: 'Un souvenir d\'enfance' },
  { id: 'fr-s8',  category: 'story',    text: 'Une fois où tu as aidé quelqu\'un' },
  // Décrire
  { id: 'fr-desc1', category: 'describe', text: 'Ta maison idéale' },
  { id: 'fr-desc2', category: 'describe', text: 'Ta ville ou ton quartier' },
  { id: 'fr-desc3', category: 'describe', text: 'Ton espace de travail' },
  { id: 'fr-desc4', category: 'describe', text: 'Quelqu\'un qui t\'inspire' },
  { id: 'fr-desc5', category: 'describe', text: 'Ton endroit préféré dans le monde' },
  { id: 'fr-desc6', category: 'describe', text: 'Un livre ou film qui t\'a marqué(e)' },
  { id: 'fr-desc7', category: 'describe', text: 'Ton travail idéal' },
  { id: 'fr-desc8', category: 'describe', text: 'Une compétence que tu veux développer' },
  // Abstrait
  { id: 'fr-a1',  category: 'abstract', text: 'Que signifie le succès pour toi ?' },
  { id: 'fr-a2',  category: 'abstract', text: 'Qu\'est-ce qui fait un bon ami ?' },
  { id: 'fr-a3',  category: 'abstract', text: 'C\'est quoi le courage ?' },
  { id: 'fr-a4',  category: 'abstract', text: 'Que représente le mot "chez soi" pour toi ?' },
  { id: 'fr-a5',  category: 'abstract', text: 'Que ferais-tu avec un temps illimité ?' },
  { id: 'fr-a6',  category: 'abstract', text: 'Quelle est la chose la plus difficile dans le fait d\'être humain ?' },
  { id: 'fr-a7',  category: 'abstract', text: 'Que représente la créativité pour toi ?' },
  { id: 'fr-a8',  category: 'abstract', text: 'Si tu pouvais changer une chose dans la société' },
  // Mot
  { id: 'fr-w1',  category: 'word', text: 'Liberté' },
  { id: 'fr-w2',  category: 'word', text: 'Temps' },
  { id: 'fr-w3',  category: 'word', text: 'Confiance' },
  { id: 'fr-w4',  category: 'word', text: 'Changement' },
  { id: 'fr-w5',  category: 'word', text: 'Silence' },
  { id: 'fr-w6',  category: 'word', text: 'Peur' },
  { id: 'fr-w7',  category: 'word', text: 'Ambition' },
  { id: 'fr-w8',  category: 'word', text: 'Beauté' },
  { id: 'fr-w9',  category: 'word', text: 'Travail' },
  { id: 'fr-w10', category: 'word', text: 'Mémoire' },
  { id: 'fr-w11', category: 'word', text: 'Risque' },
  { id: 'fr-w12', category: 'word', text: 'Confort' },
  { id: 'fr-w13', category: 'word', text: 'Patience' },
  { id: 'fr-w14', category: 'word', text: 'Bonheur' },
  { id: 'fr-w15', category: 'word', text: 'Échec' },
  { id: 'fr-w16', category: 'word', text: 'Nature' },
  { id: 'fr-w17', category: 'word', text: 'Routine' },
  { id: 'fr-w18', category: 'word', text: 'Solitude' },
  { id: 'fr-w19', category: 'word', text: 'Loyauté' },
  { id: 'fr-w20', category: 'word', text: 'Pouvoir' },
]

const ES: Topic[] = [
  { id: 'es-d1',    category: 'daily',    text: 'Tu rutina matutina' },
  { id: 'es-d2',    category: 'daily',    text: 'Cómo pasas tus tardes' },
  { id: 'es-d3',    category: 'daily',    text: 'Tu trayecto diario' },
  { id: 'es-d4',    category: 'daily',    text: 'Cocinar un plato que te encanta' },
  { id: 'es-d5',    category: 'daily',    text: 'Un fin de semana típico' },
  { id: 'es-d6',    category: 'daily',    text: 'Cómo te organizas' },
  { id: 'es-d7',    category: 'daily',    text: 'Tus hábitos de sueño' },
  { id: 'es-d8',    category: 'daily',    text: 'Hacer la compra' },
  { id: 'es-o1',    category: 'opinion',  text: 'El mejor invento de los últimos 20 años' },
  { id: 'es-o2',    category: 'opinion',  text: 'Redes sociales — ¿buenas o malas?' },
  { id: 'es-o3',    category: 'opinion',  text: 'Trabajo remoto vs oficina' },
  { id: 'es-o4',    category: 'opinion',  text: '¿Todos deberían aprender a programar?' },
  { id: 'es-o5',    category: 'opinion',  text: 'Dinero vs felicidad' },
  { id: 'es-o6',    category: 'opinion',  text: '¿Es mejor vivir en ciudad o en el campo?' },
  { id: 'es-o7',    category: 'opinion',  text: 'La importancia de los hobbies' },
  { id: 'es-o8',    category: 'opinion',  text: '¿Deberían las escuelas enseñar finanzas?' },
  { id: 'es-s1',    category: 'story',    text: 'Un error que te enseñó algo' },
  { id: 'es-s2',    category: 'story',    text: 'Un viaje que te cambió' },
  { id: 'es-s3',    category: 'story',    text: 'La mejor decisión que tomaste' },
  { id: 'es-s4',    category: 'story',    text: 'Una vez que estuviste muy nervioso/a' },
  { id: 'es-s5',    category: 'story',    text: 'Algo que aprendiste a la fuerza' },
  { id: 'es-s6',    category: 'story',    text: 'Un momento del que te sentiste orgulloso/a' },
  { id: 'es-s7',    category: 'story',    text: 'Un recuerdo de infancia' },
  { id: 'es-s8',    category: 'story',    text: 'Una vez que ayudaste a alguien' },
  { id: 'es-desc1', category: 'describe', text: 'Tu hogar ideal' },
  { id: 'es-desc2', category: 'describe', text: 'Tu ciudad o barrio' },
  { id: 'es-desc3', category: 'describe', text: 'Tu espacio de trabajo' },
  { id: 'es-desc4', category: 'describe', text: 'Alguien que te inspira' },
  { id: 'es-desc5', category: 'describe', text: 'Tu lugar favorito del mundo' },
  { id: 'es-desc6', category: 'describe', text: 'Un libro o película que te marcó' },
  { id: 'es-desc7', category: 'describe', text: 'Tu trabajo ideal' },
  { id: 'es-desc8', category: 'describe', text: 'Una habilidad que quieres desarrollar' },
  { id: 'es-a1',    category: 'abstract', text: '¿Qué significa el éxito para ti?' },
  { id: 'es-a2',    category: 'abstract', text: '¿Qué hace a un buen amigo?' },
  { id: 'es-a3',    category: 'abstract', text: '¿Qué es el coraje?' },
  { id: 'es-a4',    category: 'abstract', text: '¿Qué significa el hogar para ti?' },
  { id: 'es-a5',    category: 'abstract', text: '¿Qué harías con tiempo ilimitado?' },
  { id: 'es-a6',    category: 'abstract', text: '¿Qué es lo más difícil de ser humano?' },
  { id: 'es-a7',    category: 'abstract', text: '¿Qué significa la creatividad para ti?' },
  { id: 'es-a8',    category: 'abstract', text: 'Si pudieras cambiar algo de la sociedad' },
  { id: 'es-w1',  category: 'word', text: 'Libertad' },
  { id: 'es-w2',  category: 'word', text: 'Tiempo' },
  { id: 'es-w3',  category: 'word', text: 'Confianza' },
  { id: 'es-w4',  category: 'word', text: 'Cambio' },
  { id: 'es-w5',  category: 'word', text: 'Silencio' },
  { id: 'es-w6',  category: 'word', text: 'Miedo' },
  { id: 'es-w7',  category: 'word', text: 'Ambición' },
  { id: 'es-w8',  category: 'word', text: 'Belleza' },
  { id: 'es-w9',  category: 'word', text: 'Trabajo' },
  { id: 'es-w10', category: 'word', text: 'Memoria' },
  { id: 'es-w11', category: 'word', text: 'Riesgo' },
  { id: 'es-w12', category: 'word', text: 'Comodidad' },
  { id: 'es-w13', category: 'word', text: 'Paciencia' },
  { id: 'es-w14', category: 'word', text: 'Felicidad' },
  { id: 'es-w15', category: 'word', text: 'Fracaso' },
  { id: 'es-w16', category: 'word', text: 'Naturaleza' },
  { id: 'es-w17', category: 'word', text: 'Rutina' },
  { id: 'es-w18', category: 'word', text: 'Soledad' },
  { id: 'es-w19', category: 'word', text: 'Lealtad' },
  { id: 'es-w20', category: 'word', text: 'Poder' },
]

const AR: Topic[] = [
  { id: 'ar-d1',    category: 'daily',    text: 'روتينك الصباحي' },
  { id: 'ar-d2',    category: 'daily',    text: 'كيف تقضي أمسياتك' },
  { id: 'ar-d3',    category: 'daily',    text: 'تنقلك اليومي' },
  { id: 'ar-d4',    category: 'daily',    text: 'طبخ طبق تحبه' },
  { id: 'ar-d5',    category: 'daily',    text: 'عطلة نهاية أسبوع عادية' },
  { id: 'ar-d6',    category: 'daily',    text: 'كيف تنظم وقتك' },
  { id: 'ar-d7',    category: 'daily',    text: 'عاداتك في النوم' },
  { id: 'ar-d8',    category: 'daily',    text: 'التسوق للمواد الغذائية' },
  { id: 'ar-o1',    category: 'opinion',  text: 'أفضل اختراع في السنوات العشرين الأخيرة' },
  { id: 'ar-o2',    category: 'opinion',  text: 'وسائل التواصل الاجتماعي — جيدة أم سيئة؟' },
  { id: 'ar-o3',    category: 'opinion',  text: 'العمل عن بُعد مقابل المكتب' },
  { id: 'ar-o4',    category: 'opinion',  text: 'هل يجب أن يتعلم الجميع البرمجة؟' },
  { id: 'ar-o5',    category: 'opinion',  text: 'المال مقابل السعادة' },
  { id: 'ar-o6',    category: 'opinion',  text: 'هل الحياة في المدينة أفضل من الريف؟' },
  { id: 'ar-o7',    category: 'opinion',  text: 'أهمية الهوايات' },
  { id: 'ar-o8',    category: 'opinion',  text: 'هل يجب أن تعلّم المدارس الثقافة المالية؟' },
  { id: 'ar-s1',    category: 'story',    text: 'خطأ علّمك شيئاً' },
  { id: 'ar-s2',    category: 'story',    text: 'رحلة غيّرتك' },
  { id: 'ar-s3',    category: 'story',    text: 'أفضل قرار اتخذته' },
  { id: 'ar-s4',    category: 'story',    text: 'لحظة كنت فيها متوتراً جداً' },
  { id: 'ar-s5',    category: 'story',    text: 'شيء تعلمته بالطريقة الصعبة' },
  { id: 'ar-s6',    category: 'story',    text: 'لحظة افتخرت فيها بنفسك' },
  { id: 'ar-s7',    category: 'story',    text: 'ذكرى من الطفولة' },
  { id: 'ar-s8',    category: 'story',    text: 'مرة ساعدت فيها شخصاً ما' },
  { id: 'ar-desc1', category: 'describe', text: 'منزلك المثالي' },
  { id: 'ar-desc2', category: 'describe', text: 'مدينتك أو حيّك' },
  { id: 'ar-desc3', category: 'describe', text: 'مساحة عملك' },
  { id: 'ar-desc4', category: 'describe', text: 'شخص يلهمك' },
  { id: 'ar-desc5', category: 'describe', text: 'مكانك المفضل في العالم' },
  { id: 'ar-desc6', category: 'describe', text: 'كتاب أو فيلم بقي في ذاكرتك' },
  { id: 'ar-desc7', category: 'describe', text: 'وظيفتك المثالية' },
  { id: 'ar-desc8', category: 'describe', text: 'مهارة تريد تطويرها' },
  { id: 'ar-a1',    category: 'abstract', text: 'ماذا يعني النجاح بالنسبة لك؟' },
  { id: 'ar-a2',    category: 'abstract', text: 'ما الذي يجعل الصديق الجيد؟' },
  { id: 'ar-a3',    category: 'abstract', text: 'ما هي الشجاعة؟' },
  { id: 'ar-a4',    category: 'abstract', text: 'ماذا يعني الوطن بالنسبة لك؟' },
  { id: 'ar-a5',    category: 'abstract', text: 'ماذا ستفعل بوقت غير محدود؟' },
  { id: 'ar-a6',    category: 'abstract', text: 'ما أصعب شيء في كوننا بشراً؟' },
  { id: 'ar-a7',    category: 'abstract', text: 'ماذا تعني الإبداع بالنسبة لك؟' },
  { id: 'ar-a8',    category: 'abstract', text: 'لو استطعت تغيير شيء واحد في المجتمع' },
  { id: 'ar-w1',  category: 'word', text: 'حرية' },
  { id: 'ar-w2',  category: 'word', text: 'وقت' },
  { id: 'ar-w3',  category: 'word', text: 'ثقة' },
  { id: 'ar-w4',  category: 'word', text: 'تغيير' },
  { id: 'ar-w5',  category: 'word', text: 'صمت' },
  { id: 'ar-w6',  category: 'word', text: 'خوف' },
  { id: 'ar-w7',  category: 'word', text: 'طموح' },
  { id: 'ar-w8',  category: 'word', text: 'جمال' },
  { id: 'ar-w9',  category: 'word', text: 'عمل' },
  { id: 'ar-w10', category: 'word', text: 'ذاكرة' },
  { id: 'ar-w11', category: 'word', text: 'مخاطرة' },
  { id: 'ar-w12', category: 'word', text: 'راحة' },
  { id: 'ar-w13', category: 'word', text: 'صبر' },
  { id: 'ar-w14', category: 'word', text: 'سعادة' },
  { id: 'ar-w15', category: 'word', text: 'فشل' },
  { id: 'ar-w16', category: 'word', text: 'طبيعة' },
  { id: 'ar-w17', category: 'word', text: 'روتين' },
  { id: 'ar-w18', category: 'word', text: 'وحدة' },
  { id: 'ar-w19', category: 'word', text: 'وفاء' },
  { id: 'ar-w20', category: 'word', text: 'قوة' },
]

const JA: Topic[] = [
  { id: 'ja-d1',    category: 'daily',    text: '朝のルーティン' },
  { id: 'ja-d2',    category: 'daily',    text: '夜の過ごし方' },
  { id: 'ja-d3',    category: 'daily',    text: '毎日の通勤・通学' },
  { id: 'ja-d4',    category: 'daily',    text: '好きな料理を作ること' },
  { id: 'ja-d5',    category: 'daily',    text: 'いつもの週末' },
  { id: 'ja-d6',    category: 'daily',    text: '自分の整理術' },
  { id: 'ja-d7',    category: 'daily',    text: '睡眠習慣' },
  { id: 'ja-d8',    category: 'daily',    text: '買い物' },
  { id: 'ja-o1',    category: 'opinion',  text: 'この20年で最高の発明' },
  { id: 'ja-o2',    category: 'opinion',  text: 'SNS — 良い？悪い？' },
  { id: 'ja-o3',    category: 'opinion',  text: 'リモートワーク vs 出社' },
  { id: 'ja-o4',    category: 'opinion',  text: '全員がプログラミングを学ぶべき？' },
  { id: 'ja-o5',    category: 'opinion',  text: 'お金 vs 幸福' },
  { id: 'ja-o6',    category: 'opinion',  text: '都会と田舎、どちらが良い？' },
  { id: 'ja-o7',    category: 'opinion',  text: '趣味の大切さ' },
  { id: 'ja-o8',    category: 'opinion',  text: '学校でお金の教育をすべき？' },
  { id: 'ja-s1',    category: 'story',    text: '何かを教えてくれた失敗' },
  { id: 'ja-s2',    category: 'story',    text: 'あなたを変えた旅' },
  { id: 'ja-s3',    category: 'story',    text: '今までで最高の決断' },
  { id: 'ja-s4',    category: 'story',    text: '本当に緊張した瞬間' },
  { id: 'ja-s5',    category: 'story',    text: '苦労して学んだこと' },
  { id: 'ja-s6',    category: 'story',    text: '自分を誇りに思った瞬間' },
  { id: 'ja-s7',    category: 'story',    text: '子供の頃の思い出' },
  { id: 'ja-s8',    category: 'story',    text: '誰かを助けたとき' },
  { id: 'ja-desc1', category: 'describe', text: '理想の家' },
  { id: 'ja-desc2', category: 'describe', text: 'あなたの街や近所' },
  { id: 'ja-desc3', category: 'describe', text: '作業スペース' },
  { id: 'ja-desc4', category: 'describe', text: 'あなたに影響を与えた人' },
  { id: 'ja-desc5', category: 'describe', text: '世界で一番好きな場所' },
  { id: 'ja-desc6', category: 'describe', text: '心に残った本や映画' },
  { id: 'ja-desc7', category: 'describe', text: '理想の仕事' },
  { id: 'ja-desc8', category: 'describe', text: '身に付けたいスキル' },
  { id: 'ja-a1',    category: 'abstract', text: '成功とはあなたにとって何？' },
  { id: 'ja-a2',    category: 'abstract', text: '良い友人とは？' },
  { id: 'ja-a3',    category: 'abstract', text: '勇気とは何か？' },
  { id: 'ja-a4',    category: 'abstract', text: '「家」とはあなたにとって何？' },
  { id: 'ja-a5',    category: 'abstract', text: '無限の時間があったら何をする？' },
  { id: 'ja-a6',    category: 'abstract', text: '人間であることで一番難しいことは？' },
  { id: 'ja-a7',    category: 'abstract', text: '創造性とはあなたにとって何？' },
  { id: 'ja-a8',    category: 'abstract', text: '社会で一つ変えられるとしたら' },
  { id: 'ja-w1',  category: 'word', text: '自由' },
  { id: 'ja-w2',  category: 'word', text: '時間' },
  { id: 'ja-w3',  category: 'word', text: '信頼' },
  { id: 'ja-w4',  category: 'word', text: '変化' },
  { id: 'ja-w5',  category: 'word', text: '沈黙' },
  { id: 'ja-w6',  category: 'word', text: '恐れ' },
  { id: 'ja-w7',  category: 'word', text: '野心' },
  { id: 'ja-w8',  category: 'word', text: '美しさ' },
  { id: 'ja-w9',  category: 'word', text: '仕事' },
  { id: 'ja-w10', category: 'word', text: '記憶' },
  { id: 'ja-w11', category: 'word', text: 'リスク' },
  { id: 'ja-w12', category: 'word', text: '安らぎ' },
  { id: 'ja-w13', category: 'word', text: '忍耐' },
  { id: 'ja-w14', category: 'word', text: '幸福' },
  { id: 'ja-w15', category: 'word', text: '失敗' },
  { id: 'ja-w16', category: 'word', text: '自然' },
  { id: 'ja-w17', category: 'word', text: '日常' },
  { id: 'ja-w18', category: 'word', text: '孤独' },
  { id: 'ja-w19', category: 'word', text: '誠実' },
  { id: 'ja-w20', category: 'word', text: '力' },
]

export const TOPICS: Record<Language, Topic[]> = { en: EN, fr: FR, es: ES, ar: AR, ja: JA }

export const CATEGORY_LABELS: Record<string, Record<Language, string>> = {
  daily:    { en: 'Daily Life',  fr: 'Vie quotidienne', es: 'Vida cotidiana',  ar: 'الحياة اليومية', ja: '日常生活' },
  opinion:  { en: 'Opinion',    fr: 'Opinion',          es: 'Opinión',         ar: 'رأي',            ja: '意見'    },
  story:    { en: 'Story',      fr: 'Histoire',         es: 'Historia',        ar: 'قصة',            ja: '物語'    },
  describe: { en: 'Describe',   fr: 'Décrire',          es: 'Describir',       ar: 'وصف',            ja: '描写'    },
  abstract: { en: 'Abstract',   fr: 'Abstrait',         es: 'Abstracto',       ar: 'مجرد',           ja: '抽象的'  },
  word:     { en: 'Word',       fr: 'Mot',              es: 'Palabra',         ar: 'كلمة',           ja: '言葉'    },
}

export const CATEGORY_HINTS: Record<Category, Record<Language, string[]>> = {
  daily: {
    en: ['describe your typical routine', 'what do you enjoy or dislike about it?', 'has it changed recently?'],
    fr: ['décris ta routine habituelle', 'qu\'est-ce que tu aimes ou pas ?', 'est-ce que ça a changé récemment ?'],
    es: ['describe tu rutina habitual', '¿qué te gusta o no te gusta?', '¿ha cambiado recientemente?'],
    ar: ['صف روتينك المعتاد', 'ما الذي تحبه أو لا تحبه؟', 'هل تغير مؤخراً؟'],
    ja: ['普段のルーティンを説明して', '好きなこと・嫌なことは？', '最近変化はあった？'],
  },
  opinion: {
    en: ['state your main position clearly', 'give one or two reasons why', 'acknowledge a counterargument'],
    fr: ['énonce clairement ta position', 'donne une ou deux raisons', 'reconnais un contre-argument'],
    es: ['expresa tu posición claramente', 'da una o dos razones', 'reconoce un contraargumento'],
    ar: ['وضح موقفك بشكل واضح', 'أعطِ سبباً أو سببين', 'اعترف بحجة مضادة'],
    ja: ['自分の立場をはっきり言う', '理由を1〜2つ挙げる', '反論にも触れる'],
  },
  story: {
    en: ['set the scene — when, where, who', 'what happened step by step', 'what did you take away from it?'],
    fr: ['campe le décor — quand, où, qui', 'raconte ce qui s\'est passé', 'qu\'est-ce que ça t\'a appris ?'],
    es: ['sitúa la escena — cuándo, dónde, quién', 'cuenta lo que pasó paso a paso', '¿qué aprendiste?'],
    ar: ['حدد المشهد — متى، أين، من', 'اروِ ما حدث خطوة بخطوة', 'ماذا تعلمت؟'],
    ja: ['場面を設定する — いつ、どこ、誰', '何が起きたか順番に話す', '何を学んだ？'],
  },
  describe: {
    en: ['paint a picture with specific details', 'how does it make you feel?', 'why is it meaningful to you?'],
    fr: ['donne des détails précis', 'qu\'est-ce que ça t\'évoque ?', 'pourquoi c\'est important pour toi ?'],
    es: ['describe con detalles específicos', '¿cómo te hace sentir?', '¿por qué es importante para ti?'],
    ar: ['صف بتفاصيل محددة', 'كيف يجعلك تشعر؟', 'لماذا هو مهم بالنسبة لك؟'],
    ja: ['具体的な詳細を描写する', 'どんな気持ちになる？', 'なぜ大切なの？'],
  },
  abstract: {
    en: ['define it in your own words', 'give a concrete example from your life', 'why does it matter to you?'],
    fr: ['définis-le avec tes propres mots', 'donne un exemple concret de ta vie', 'pourquoi est-ce important ?'],
    es: ['defínelo con tus propias palabras', 'da un ejemplo concreto de tu vida', '¿por qué importa?'],
    ar: ['عرّفه بكلماتك الخاصة', 'أعطِ مثالاً ملموساً من حياتك', 'لماذا يهمك؟'],
    ja: ['自分の言葉で定義する', '自分の経験から具体例を挙げる', 'なぜ大切なの？'],
  },
  word: {
    en: ['what does this word mean to you personally?', 'share a memory or moment linked to it', 'is it positive, negative, or both?'],
    fr: ['que représente ce mot pour toi ?', 'un souvenir ou moment lié à ce mot', 'positif, négatif, ou les deux ?'],
    es: ['¿qué significa esta palabra para ti?', 'comparte un recuerdo ligado a ella', '¿es positiva, negativa o ambas?'],
    ar: ['ماذا تعني هذه الكلمة بالنسبة لك؟', 'شارك ذكرى أو لحظة مرتبطة بها', 'هل هي إيجابية أم سلبية؟'],
    ja: ['この言葉はあなたにとって何？', 'この言葉に関連する思い出を話す', 'ポジティブ？ネガティブ？両方？'],
  },
}

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr]
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}

export function createTopicQueue(lang: Language): Topic[] {
  return shuffle(TOPICS[lang])
}
